### ISSUE TITLE
main_color = invalid!

### ISSUE THREAD

**Issue by dannypilkington** [DJj123dj/open-ticket#10]
changed the main_color numerous times but still not working... error code: -> open-ticket CONFIG ERROR: 'main_color' | invalid color!

**Comment by DJj123dj** [comment]
and what do you have written in the main color? it must be a hex-color, something like this: #123abc

**Comment by dannypilkington** [comment]
Tried everything from numbers, hex-colors, wording such as "RED"

**Comment by dannypilkington** [comment]
* Can be a number, hex string, an RGB array like:
   * ```js
   * [255, 0, 255] // purple
   * ```
   * or one of the following strings:
   * - `DEFAULT`
   * - `WHITE`
   * - `AQUA`
   * - `GREEN`
   * - `BLUE`
   * - `YELLOW`
   * - `PURPLE`
   * - `LUMINOUS_VIVID_PINK`
   * - `FUCHSIA`
   * - `GOLD`
   * - `ORANGE`
   * - `RED`
   * - `GREY`
   * - `NAVY`
   * - `DARK_AQUA`
   * - `DARK_GREEN`
   * - `DARK_BLUE`
   * - `DARK_PURPLE`
   * - `DARK_VIVID_PINK`
   * - `DARK_GOLD`
   * - `DARK_ORANGE`
   * - `DARK_RED`
   * - `DARK_GREY`
   * - `DARKER_GREY`
   * - `LIGHT_GREY`
   * - `DARK_NAVY`
   * - `BLURPLE`
   * - `GREYPLE`
   * - `DARK_BUT_NOT_BLACK`
   * - `NOT_QUITE_BLACK`
   * - `RANDOM`

Tried all of the above ^^

**Comment by DJj123dj** [comment]
Open Ticket has blocked other sorts of colors, but in future versions i will add it to the bot.

**Comment by DJj123dj** [comment]
if you have any questions, you can say it.

Have a nice day!

**Comment by dannypilkington** [comment]
managed to fix it! thanks again DJ
