### ISSUE TITLE
Claim and Unclaim not found

### ISSUE THREAD

**Issue by josuens** [DJj123dj/open-ticket#58]
The claim and unclaim commands are not working for me

[https://cdn.discordapp.com/attachments/872146290002264074/1097621010196476034/image.png](url)

**Comment by DJj123dj** [comment]
I will try to fix it in the next update, the issue has something to do with the reply speed of the interaction. With other words: the bot replies to slow

**Comment by DJj123dj** [comment]
this error is fixed in version v3.3.2!
