### ISSUE TITLE
Respond new ticket

### ISSUE THREAD

**Issue by josuens** [DJj123dj/open-ticket#61]
I am seeing that when a ticket is created, the response message does not remain in ephemeral mode

![](https://i.imgur.com/zE2XEBz.png)

**Comment by HugoTorres-AISM** [comment]
Según tengo entendido es posible activarlo o desactivarlo, revisa tu `config.json`

**Comment by josuens** [comment]
Si esta activo, solo que en este nuevo release creo que algo falto, porque a pesar que esta activo la configuración continua respondiendo sin el modo ephemeral

**Comment by josuens** [comment]
![](https://i.imgur.com/kPEeS8W.png)

**Comment by DJj123dj** [comment]
Yes I made a typo (again), it will be fixed
