### ISSUE TITLE
AxiosError: Request failed with status code 414

### ISSUE THREAD

**Issue by zat0r** [DJj123dj/open-ticket#75]
hi after running support server i get this error massage witch is cose auto shutdown 

`OPEN TICKET ERROR: UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AxiosError: Request failed with status code 414".

Create a ticket in our support server for more information!
If you do this, you might help us to avoid a future bug!`

**Comment by DJj123dj** [comment]
are you using the latest version?
3.4.0 or 3.4.1
