### ISSUE TITLE
[BUG] your bug

### ISSUE THREAD

**Issue by Miercoe** [DJj123dj/open-ticket#79]
Works fine but when you close a ticket there's no transcript html anywhere

**Comment by Sank34** [comment]
Hello! Please make sure you have configured the [html transcript configuration file](https://github.com/DJj123dj/open-ticket/blob/main/transcriptconfig.json) correctly.

**Comment by Miercoe** [comment]
> Hello! Please make sure you have configured the [html transcript configuration file](https://github.com/DJj123dj/open-ticket/blob/main/transcriptconfig.json) correctly.

thx I fixed it

**Comment by Miercoe** [comment]
> Hello! Please make sure you have configured the [html transcript configuration file](https://github.com/DJj123dj/open-ticket/blob/main/transcriptconfig.json) correctly.

sorry bro but I thought it was working but its not when I close a ticket there's nothing in the transcript channel

**Comment by Sank34** [comment]
Make sure your bot has the right permissions set.

**Comment by Miercoe** [comment]
> Make sure your bot has the right permissions set.

my bot has admin permissions bro

**Comment by Sank34** [comment]
hmm, okay, please open a ticket on our discord server so we can take a closer look at the issue.
